#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="hoctuvung")]
	public partial class hoctuvungLINQDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBanbe(Banbe instance);
    partial void UpdateBanbe(Banbe instance);
    partial void DeleteBanbe(Banbe instance);
    partial void InsertTuVung(TuVung instance);
    partial void UpdateTuVung(TuVung instance);
    partial void DeleteTuVung(TuVung instance);
    partial void InsertCauHoi_DienDan(CauHoi_DienDan instance);
    partial void UpdateCauHoi_DienDan(CauHoi_DienDan instance);
    partial void DeleteCauHoi_DienDan(CauHoi_DienDan instance);
    partial void InsertLoaiTu(LoaiTu instance);
    partial void UpdateLoaiTu(LoaiTu instance);
    partial void DeleteLoaiTu(LoaiTu instance);
    partial void InsertNguoiDung(NguoiDung instance);
    partial void UpdateNguoiDung(NguoiDung instance);
    partial void DeleteNguoiDung(NguoiDung instance);
    partial void InsertNhom_TuDien(Nhom_TuDien instance);
    partial void UpdateNhom_TuDien(Nhom_TuDien instance);
    partial void DeleteNhom_TuDien(Nhom_TuDien instance);
    partial void InsertTinNhan(TinNhan instance);
    partial void UpdateTinNhan(TinNhan instance);
    partial void DeleteTinNhan(TinNhan instance);
    partial void InsertTraLoi_DienDan(TraLoi_DienDan instance);
    partial void UpdateTraLoi_DienDan(TraLoi_DienDan instance);
    partial void DeleteTraLoi_DienDan(TraLoi_DienDan instance);
    partial void InsertTuDien(TuDien instance);
    partial void UpdateTuDien(TuDien instance);
    partial void DeleteTuDien(TuDien instance);
    #endregion
		
		public hoctuvungLINQDataContext() : 
				base(global::DAO.Properties.Settings.Default.hoctuvungConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public hoctuvungLINQDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public hoctuvungLINQDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public hoctuvungLINQDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public hoctuvungLINQDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Banbe> Banbes
		{
			get
			{
				return this.GetTable<Banbe>();
			}
		}
		
		public System.Data.Linq.Table<TuVung> TuVungs
		{
			get
			{
				return this.GetTable<TuVung>();
			}
		}
		
		public System.Data.Linq.Table<CauHoi_DienDan> CauHoi_DienDans
		{
			get
			{
				return this.GetTable<CauHoi_DienDan>();
			}
		}
		
		public System.Data.Linq.Table<LoaiTu> LoaiTus
		{
			get
			{
				return this.GetTable<LoaiTu>();
			}
		}
		
		public System.Data.Linq.Table<NguoiDung> NguoiDungs
		{
			get
			{
				return this.GetTable<NguoiDung>();
			}
		}
		
		public System.Data.Linq.Table<Nhom_TuDien> Nhom_TuDiens
		{
			get
			{
				return this.GetTable<Nhom_TuDien>();
			}
		}
		
		public System.Data.Linq.Table<TinNhan> TinNhans
		{
			get
			{
				return this.GetTable<TinNhan>();
			}
		}
		
		public System.Data.Linq.Table<TraLoi_DienDan> TraLoi_DienDans
		{
			get
			{
				return this.GetTable<TraLoi_DienDan>();
			}
		}
		
		public System.Data.Linq.Table<TuDien> TuDiens
		{
			get
			{
				return this.GetTable<TuDien>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Banbe")]
	public partial class Banbe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _taikhoan;
		
		private string _taikhoanban;
		
		private EntityRef<NguoiDung> _NguoiDung;
		
		private EntityRef<NguoiDung> _NguoiDung1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntaikhoanChanging(string value);
    partial void OntaikhoanChanged();
    partial void OntaikhoanbanChanging(string value);
    partial void OntaikhoanbanChanged();
    #endregion
		
		public Banbe()
		{
			this._NguoiDung = default(EntityRef<NguoiDung>);
			this._NguoiDung1 = default(EntityRef<NguoiDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taikhoan", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string taikhoan
		{
			get
			{
				return this._taikhoan;
			}
			set
			{
				if ((this._taikhoan != value))
				{
					if (this._NguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OntaikhoanChanging(value);
					this.SendPropertyChanging();
					this._taikhoan = value;
					this.SendPropertyChanged("taikhoan");
					this.OntaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taikhoanban", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string taikhoanban
		{
			get
			{
				return this._taikhoanban;
			}
			set
			{
				if ((this._taikhoanban != value))
				{
					if (this._NguoiDung1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OntaikhoanbanChanging(value);
					this.SendPropertyChanging();
					this._taikhoanban = value;
					this.SendPropertyChanged("taikhoanban");
					this.OntaikhoanbanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_Banbe", Storage="_NguoiDung", ThisKey="taikhoan", OtherKey="taikhoan", IsForeignKey=true)]
		public NguoiDung NguoiDung
		{
			get
			{
				return this._NguoiDung.Entity;
			}
			set
			{
				NguoiDung previousValue = this._NguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._NguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiDung.Entity = null;
						previousValue.Banbes.Remove(this);
					}
					this._NguoiDung.Entity = value;
					if ((value != null))
					{
						value.Banbes.Add(this);
						this._taikhoan = value.taikhoan;
					}
					else
					{
						this._taikhoan = default(string);
					}
					this.SendPropertyChanged("NguoiDung");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_Banbe1", Storage="_NguoiDung1", ThisKey="taikhoanban", OtherKey="taikhoan", IsForeignKey=true)]
		public NguoiDung NguoiDung1
		{
			get
			{
				return this._NguoiDung1.Entity;
			}
			set
			{
				NguoiDung previousValue = this._NguoiDung1.Entity;
				if (((previousValue != value) 
							|| (this._NguoiDung1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiDung1.Entity = null;
						previousValue.Banbes1.Remove(this);
					}
					this._NguoiDung1.Entity = value;
					if ((value != null))
					{
						value.Banbes1.Add(this);
						this._taikhoanban = value.taikhoan;
					}
					else
					{
						this._taikhoanban = default(string);
					}
					this.SendPropertyChanged("NguoiDung1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TuVung")]
	public partial class TuVung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _TuVungID;
		
		private System.Nullable<int> _LoaiTuID;
		
		private string _TuVung1;
		
		private string _NghiaTu;
		
		private string _Hinhanh;
		
		private string _Vidu;
		
		private string _taikhoan;
		
		private System.Nullable<int> _SoLanSuDung;
		
		private System.Nullable<int> _SoLanSai;
		
		private System.Nullable<bool> _kiemduyet;
		
		private System.Nullable<System.Guid> _TuDienID;
		
		private EntityRef<LoaiTu> _LoaiTu;
		
		private EntityRef<NguoiDung> _NguoiDung;
		
		private EntityRef<TuDien> _TuDien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTuVungIDChanging(System.Guid value);
    partial void OnTuVungIDChanged();
    partial void OnLoaiTuIDChanging(System.Nullable<int> value);
    partial void OnLoaiTuIDChanged();
    partial void OnTuVung1Changing(string value);
    partial void OnTuVung1Changed();
    partial void OnNghiaTuChanging(string value);
    partial void OnNghiaTuChanged();
    partial void OnHinhanhChanging(string value);
    partial void OnHinhanhChanged();
    partial void OnViduChanging(string value);
    partial void OnViduChanged();
    partial void OntaikhoanChanging(string value);
    partial void OntaikhoanChanged();
    partial void OnSoLanSuDungChanging(System.Nullable<int> value);
    partial void OnSoLanSuDungChanged();
    partial void OnSoLanSaiChanging(System.Nullable<int> value);
    partial void OnSoLanSaiChanged();
    partial void OnkiemduyetChanging(System.Nullable<bool> value);
    partial void OnkiemduyetChanged();
    partial void OnTuDienIDChanging(System.Nullable<System.Guid> value);
    partial void OnTuDienIDChanged();
    #endregion
		
		public TuVung()
		{
			this._LoaiTu = default(EntityRef<LoaiTu>);
			this._NguoiDung = default(EntityRef<NguoiDung>);
			this._TuDien = default(EntityRef<TuDien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuVungID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid TuVungID
		{
			get
			{
				return this._TuVungID;
			}
			set
			{
				if ((this._TuVungID != value))
				{
					this.OnTuVungIDChanging(value);
					this.SendPropertyChanging();
					this._TuVungID = value;
					this.SendPropertyChanged("TuVungID");
					this.OnTuVungIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiTuID", DbType="Int")]
		public System.Nullable<int> LoaiTuID
		{
			get
			{
				return this._LoaiTuID;
			}
			set
			{
				if ((this._LoaiTuID != value))
				{
					if (this._LoaiTu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLoaiTuIDChanging(value);
					this.SendPropertyChanging();
					this._LoaiTuID = value;
					this.SendPropertyChanged("LoaiTuID");
					this.OnLoaiTuIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="TuVung", Storage="_TuVung1", DbType="VarChar(30)")]
		public string TuVung1
		{
			get
			{
				return this._TuVung1;
			}
			set
			{
				if ((this._TuVung1 != value))
				{
					this.OnTuVung1Changing(value);
					this.SendPropertyChanging();
					this._TuVung1 = value;
					this.SendPropertyChanged("TuVung1");
					this.OnTuVung1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NghiaTu", DbType="NVarChar(50)")]
		public string NghiaTu
		{
			get
			{
				return this._NghiaTu;
			}
			set
			{
				if ((this._NghiaTu != value))
				{
					this.OnNghiaTuChanging(value);
					this.SendPropertyChanging();
					this._NghiaTu = value;
					this.SendPropertyChanged("NghiaTu");
					this.OnNghiaTuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinhanh", DbType="VarChar(1000)")]
		public string Hinhanh
		{
			get
			{
				return this._Hinhanh;
			}
			set
			{
				if ((this._Hinhanh != value))
				{
					this.OnHinhanhChanging(value);
					this.SendPropertyChanging();
					this._Hinhanh = value;
					this.SendPropertyChanged("Hinhanh");
					this.OnHinhanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vidu", DbType="VarChar(4000)")]
		public string Vidu
		{
			get
			{
				return this._Vidu;
			}
			set
			{
				if ((this._Vidu != value))
				{
					this.OnViduChanging(value);
					this.SendPropertyChanging();
					this._Vidu = value;
					this.SendPropertyChanged("Vidu");
					this.OnViduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taikhoan", DbType="VarChar(30)")]
		public string taikhoan
		{
			get
			{
				return this._taikhoan;
			}
			set
			{
				if ((this._taikhoan != value))
				{
					if (this._NguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OntaikhoanChanging(value);
					this.SendPropertyChanging();
					this._taikhoan = value;
					this.SendPropertyChanged("taikhoan");
					this.OntaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLanSuDung", DbType="Int")]
		public System.Nullable<int> SoLanSuDung
		{
			get
			{
				return this._SoLanSuDung;
			}
			set
			{
				if ((this._SoLanSuDung != value))
				{
					this.OnSoLanSuDungChanging(value);
					this.SendPropertyChanging();
					this._SoLanSuDung = value;
					this.SendPropertyChanged("SoLanSuDung");
					this.OnSoLanSuDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLanSai", DbType="Int")]
		public System.Nullable<int> SoLanSai
		{
			get
			{
				return this._SoLanSai;
			}
			set
			{
				if ((this._SoLanSai != value))
				{
					this.OnSoLanSaiChanging(value);
					this.SendPropertyChanging();
					this._SoLanSai = value;
					this.SendPropertyChanged("SoLanSai");
					this.OnSoLanSaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kiemduyet", DbType="Bit")]
		public System.Nullable<bool> kiemduyet
		{
			get
			{
				return this._kiemduyet;
			}
			set
			{
				if ((this._kiemduyet != value))
				{
					this.OnkiemduyetChanging(value);
					this.SendPropertyChanging();
					this._kiemduyet = value;
					this.SendPropertyChanged("kiemduyet");
					this.OnkiemduyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuDienID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> TuDienID
		{
			get
			{
				return this._TuDienID;
			}
			set
			{
				if ((this._TuDienID != value))
				{
					if (this._TuDien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTuDienIDChanging(value);
					this.SendPropertyChanging();
					this._TuDienID = value;
					this.SendPropertyChanged("TuDienID");
					this.OnTuDienIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiTu_TuVung", Storage="_LoaiTu", ThisKey="LoaiTuID", OtherKey="LoaiTuID", IsForeignKey=true, DeleteRule="CASCADE")]
		public LoaiTu LoaiTu
		{
			get
			{
				return this._LoaiTu.Entity;
			}
			set
			{
				LoaiTu previousValue = this._LoaiTu.Entity;
				if (((previousValue != value) 
							|| (this._LoaiTu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiTu.Entity = null;
						previousValue.TuVungs.Remove(this);
					}
					this._LoaiTu.Entity = value;
					if ((value != null))
					{
						value.TuVungs.Add(this);
						this._LoaiTuID = value.LoaiTuID;
					}
					else
					{
						this._LoaiTuID = default(Nullable<int>);
					}
					this.SendPropertyChanged("LoaiTu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_TuVung", Storage="_NguoiDung", ThisKey="taikhoan", OtherKey="taikhoan", IsForeignKey=true, DeleteRule="CASCADE")]
		public NguoiDung NguoiDung
		{
			get
			{
				return this._NguoiDung.Entity;
			}
			set
			{
				NguoiDung previousValue = this._NguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._NguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiDung.Entity = null;
						previousValue.TuVungs.Remove(this);
					}
					this._NguoiDung.Entity = value;
					if ((value != null))
					{
						value.TuVungs.Add(this);
						this._taikhoan = value.taikhoan;
					}
					else
					{
						this._taikhoan = default(string);
					}
					this.SendPropertyChanged("NguoiDung");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TuDien_TuVung", Storage="_TuDien", ThisKey="TuDienID", OtherKey="TudienID", IsForeignKey=true)]
		public TuDien TuDien
		{
			get
			{
				return this._TuDien.Entity;
			}
			set
			{
				TuDien previousValue = this._TuDien.Entity;
				if (((previousValue != value) 
							|| (this._TuDien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TuDien.Entity = null;
						previousValue.TuVungs.Remove(this);
					}
					this._TuDien.Entity = value;
					if ((value != null))
					{
						value.TuVungs.Add(this);
						this._TuDienID = value.TudienID;
					}
					else
					{
						this._TuDienID = default(Nullable<System.Guid>);
					}
					this.SendPropertyChanged("TuDien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CauHoi_DienDan")]
	public partial class CauHoi_DienDan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _CauHoiID;
		
		private string _TieuDe;
		
		private string _NoiDung;
		
		private string _taikhoan;
		
		private System.Nullable<System.DateTime> _NgayGoi;
		
		private EntitySet<TraLoi_DienDan> _TraLoi_DienDans;
		
		private EntityRef<NguoiDung> _NguoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCauHoiIDChanging(System.Guid value);
    partial void OnCauHoiIDChanged();
    partial void OnTieuDeChanging(string value);
    partial void OnTieuDeChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OntaikhoanChanging(string value);
    partial void OntaikhoanChanged();
    partial void OnNgayGoiChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayGoiChanged();
    #endregion
		
		public CauHoi_DienDan()
		{
			this._TraLoi_DienDans = new EntitySet<TraLoi_DienDan>(new Action<TraLoi_DienDan>(this.attach_TraLoi_DienDans), new Action<TraLoi_DienDan>(this.detach_TraLoi_DienDans));
			this._NguoiDung = default(EntityRef<NguoiDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CauHoiID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid CauHoiID
		{
			get
			{
				return this._CauHoiID;
			}
			set
			{
				if ((this._CauHoiID != value))
				{
					this.OnCauHoiIDChanging(value);
					this.SendPropertyChanging();
					this._CauHoiID = value;
					this.SendPropertyChanged("CauHoiID");
					this.OnCauHoiIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDe", DbType="NVarChar(100)")]
		public string TieuDe
		{
			get
			{
				return this._TieuDe;
			}
			set
			{
				if ((this._TieuDe != value))
				{
					this.OnTieuDeChanging(value);
					this.SendPropertyChanging();
					this._TieuDe = value;
					this.SendPropertyChanged("TieuDe");
					this.OnTieuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taikhoan", DbType="VarChar(30)")]
		public string taikhoan
		{
			get
			{
				return this._taikhoan;
			}
			set
			{
				if ((this._taikhoan != value))
				{
					if (this._NguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OntaikhoanChanging(value);
					this.SendPropertyChanging();
					this._taikhoan = value;
					this.SendPropertyChanged("taikhoan");
					this.OntaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayGoi", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NgayGoi
		{
			get
			{
				return this._NgayGoi;
			}
			set
			{
				if ((this._NgayGoi != value))
				{
					this.OnNgayGoiChanging(value);
					this.SendPropertyChanging();
					this._NgayGoi = value;
					this.SendPropertyChanged("NgayGoi");
					this.OnNgayGoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CauHoi_DienDan_TraLoi_DienDan", Storage="_TraLoi_DienDans", ThisKey="CauHoiID", OtherKey="CauHoiID")]
		public EntitySet<TraLoi_DienDan> TraLoi_DienDans
		{
			get
			{
				return this._TraLoi_DienDans;
			}
			set
			{
				this._TraLoi_DienDans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_CauHoi_DienDan", Storage="_NguoiDung", ThisKey="taikhoan", OtherKey="taikhoan", IsForeignKey=true, DeleteRule="CASCADE")]
		public NguoiDung NguoiDung
		{
			get
			{
				return this._NguoiDung.Entity;
			}
			set
			{
				NguoiDung previousValue = this._NguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._NguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiDung.Entity = null;
						previousValue.CauHoi_DienDans.Remove(this);
					}
					this._NguoiDung.Entity = value;
					if ((value != null))
					{
						value.CauHoi_DienDans.Add(this);
						this._taikhoan = value.taikhoan;
					}
					else
					{
						this._taikhoan = default(string);
					}
					this.SendPropertyChanged("NguoiDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TraLoi_DienDans(TraLoi_DienDan entity)
		{
			this.SendPropertyChanging();
			entity.CauHoi_DienDan = this;
		}
		
		private void detach_TraLoi_DienDans(TraLoi_DienDan entity)
		{
			this.SendPropertyChanging();
			entity.CauHoi_DienDan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiTu")]
	public partial class LoaiTu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LoaiTuID;
		
		private string _Ten_Anh;
		
		private string _Ten_Viet;
		
		private EntitySet<TuVung> _TuVungs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLoaiTuIDChanging(int value);
    partial void OnLoaiTuIDChanged();
    partial void OnTen_AnhChanging(string value);
    partial void OnTen_AnhChanged();
    partial void OnTen_VietChanging(string value);
    partial void OnTen_VietChanged();
    #endregion
		
		public LoaiTu()
		{
			this._TuVungs = new EntitySet<TuVung>(new Action<TuVung>(this.attach_TuVungs), new Action<TuVung>(this.detach_TuVungs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiTuID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LoaiTuID
		{
			get
			{
				return this._LoaiTuID;
			}
			set
			{
				if ((this._LoaiTuID != value))
				{
					this.OnLoaiTuIDChanging(value);
					this.SendPropertyChanging();
					this._LoaiTuID = value;
					this.SendPropertyChanged("LoaiTuID");
					this.OnLoaiTuIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_Anh", DbType="VarChar(50)")]
		public string Ten_Anh
		{
			get
			{
				return this._Ten_Anh;
			}
			set
			{
				if ((this._Ten_Anh != value))
				{
					this.OnTen_AnhChanging(value);
					this.SendPropertyChanging();
					this._Ten_Anh = value;
					this.SendPropertyChanged("Ten_Anh");
					this.OnTen_AnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_Viet", DbType="NVarChar(50)")]
		public string Ten_Viet
		{
			get
			{
				return this._Ten_Viet;
			}
			set
			{
				if ((this._Ten_Viet != value))
				{
					this.OnTen_VietChanging(value);
					this.SendPropertyChanging();
					this._Ten_Viet = value;
					this.SendPropertyChanged("Ten_Viet");
					this.OnTen_VietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiTu_TuVung", Storage="_TuVungs", ThisKey="LoaiTuID", OtherKey="LoaiTuID")]
		public EntitySet<TuVung> TuVungs
		{
			get
			{
				return this._TuVungs;
			}
			set
			{
				this._TuVungs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TuVungs(TuVung entity)
		{
			this.SendPropertyChanging();
			entity.LoaiTu = this;
		}
		
		private void detach_TuVungs(TuVung entity)
		{
			this.SendPropertyChanging();
			entity.LoaiTu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NguoiDung")]
	public partial class NguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _taikhoan;
		
		private string _matkhau;
		
		private string _email;
		
		private string _dt;
		
		private System.Nullable<bool> _banned;
		
		private string _quyen;
		
		private System.Nullable<bool> _bannednick;
		
		private System.Nullable<bool> _QLTDCongDong;
		
		private System.Nullable<bool> _QLTuVungCongDong;
		
		private System.Nullable<bool> _DuyetTu;
		
		private System.Nullable<bool> _XemTuVungSai;
		
		private System.Nullable<bool> _QLThongTinWeb;
		
		private System.Nullable<bool> _QLDienDan;
		
		private EntitySet<Banbe> _Banbes;
		
		private EntitySet<Banbe> _Banbes1;
		
		private EntitySet<TuVung> _TuVungs;
		
		private EntitySet<CauHoi_DienDan> _CauHoi_DienDans;
		
		private EntitySet<Nhom_TuDien> _Nhom_TuDiens;
		
		private EntitySet<TinNhan> _TinNhans;
		
		private EntitySet<TinNhan> _TinNhans1;
		
		private EntitySet<TraLoi_DienDan> _TraLoi_DienDans;
		
		private EntitySet<TuDien> _TuDiens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntaikhoanChanging(string value);
    partial void OntaikhoanChanged();
    partial void OnmatkhauChanging(string value);
    partial void OnmatkhauChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OndtChanging(string value);
    partial void OndtChanged();
    partial void OnbannedChanging(System.Nullable<bool> value);
    partial void OnbannedChanged();
    partial void OnquyenChanging(string value);
    partial void OnquyenChanged();
    partial void OnbannednickChanging(System.Nullable<bool> value);
    partial void OnbannednickChanged();
    partial void OnQLTDCongDongChanging(System.Nullable<bool> value);
    partial void OnQLTDCongDongChanged();
    partial void OnQLTuVungCongDongChanging(System.Nullable<bool> value);
    partial void OnQLTuVungCongDongChanged();
    partial void OnDuyetTuChanging(System.Nullable<bool> value);
    partial void OnDuyetTuChanged();
    partial void OnXemTuVungSaiChanging(System.Nullable<bool> value);
    partial void OnXemTuVungSaiChanged();
    partial void OnQLThongTinWebChanging(System.Nullable<bool> value);
    partial void OnQLThongTinWebChanged();
    partial void OnQLDienDanChanging(System.Nullable<bool> value);
    partial void OnQLDienDanChanged();
    #endregion
		
		public NguoiDung()
		{
			this._Banbes = new EntitySet<Banbe>(new Action<Banbe>(this.attach_Banbes), new Action<Banbe>(this.detach_Banbes));
			this._Banbes1 = new EntitySet<Banbe>(new Action<Banbe>(this.attach_Banbes1), new Action<Banbe>(this.detach_Banbes1));
			this._TuVungs = new EntitySet<TuVung>(new Action<TuVung>(this.attach_TuVungs), new Action<TuVung>(this.detach_TuVungs));
			this._CauHoi_DienDans = new EntitySet<CauHoi_DienDan>(new Action<CauHoi_DienDan>(this.attach_CauHoi_DienDans), new Action<CauHoi_DienDan>(this.detach_CauHoi_DienDans));
			this._Nhom_TuDiens = new EntitySet<Nhom_TuDien>(new Action<Nhom_TuDien>(this.attach_Nhom_TuDiens), new Action<Nhom_TuDien>(this.detach_Nhom_TuDiens));
			this._TinNhans = new EntitySet<TinNhan>(new Action<TinNhan>(this.attach_TinNhans), new Action<TinNhan>(this.detach_TinNhans));
			this._TinNhans1 = new EntitySet<TinNhan>(new Action<TinNhan>(this.attach_TinNhans1), new Action<TinNhan>(this.detach_TinNhans1));
			this._TraLoi_DienDans = new EntitySet<TraLoi_DienDan>(new Action<TraLoi_DienDan>(this.attach_TraLoi_DienDans), new Action<TraLoi_DienDan>(this.detach_TraLoi_DienDans));
			this._TuDiens = new EntitySet<TuDien>(new Action<TuDien>(this.attach_TuDiens), new Action<TuDien>(this.detach_TuDiens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taikhoan", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string taikhoan
		{
			get
			{
				return this._taikhoan;
			}
			set
			{
				if ((this._taikhoan != value))
				{
					this.OntaikhoanChanging(value);
					this.SendPropertyChanging();
					this._taikhoan = value;
					this.SendPropertyChanged("taikhoan");
					this.OntaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matkhau", DbType="VarChar(30)")]
		public string matkhau
		{
			get
			{
				return this._matkhau;
			}
			set
			{
				if ((this._matkhau != value))
				{
					this.OnmatkhauChanging(value);
					this.SendPropertyChanging();
					this._matkhau = value;
					this.SendPropertyChanged("matkhau");
					this.OnmatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dt", DbType="VarChar(12)")]
		public string dt
		{
			get
			{
				return this._dt;
			}
			set
			{
				if ((this._dt != value))
				{
					this.OndtChanging(value);
					this.SendPropertyChanging();
					this._dt = value;
					this.SendPropertyChanged("dt");
					this.OndtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_banned", DbType="Bit")]
		public System.Nullable<bool> banned
		{
			get
			{
				return this._banned;
			}
			set
			{
				if ((this._banned != value))
				{
					this.OnbannedChanging(value);
					this.SendPropertyChanging();
					this._banned = value;
					this.SendPropertyChanged("banned");
					this.OnbannedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quyen", DbType="Char(10)")]
		public string quyen
		{
			get
			{
				return this._quyen;
			}
			set
			{
				if ((this._quyen != value))
				{
					this.OnquyenChanging(value);
					this.SendPropertyChanging();
					this._quyen = value;
					this.SendPropertyChanged("quyen");
					this.OnquyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bannednick", DbType="Bit")]
		public System.Nullable<bool> bannednick
		{
			get
			{
				return this._bannednick;
			}
			set
			{
				if ((this._bannednick != value))
				{
					this.OnbannednickChanging(value);
					this.SendPropertyChanging();
					this._bannednick = value;
					this.SendPropertyChanged("bannednick");
					this.OnbannednickChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QLTDCongDong", DbType="Bit")]
		public System.Nullable<bool> QLTDCongDong
		{
			get
			{
				return this._QLTDCongDong;
			}
			set
			{
				if ((this._QLTDCongDong != value))
				{
					this.OnQLTDCongDongChanging(value);
					this.SendPropertyChanging();
					this._QLTDCongDong = value;
					this.SendPropertyChanged("QLTDCongDong");
					this.OnQLTDCongDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QLTuVungCongDong", DbType="Bit")]
		public System.Nullable<bool> QLTuVungCongDong
		{
			get
			{
				return this._QLTuVungCongDong;
			}
			set
			{
				if ((this._QLTuVungCongDong != value))
				{
					this.OnQLTuVungCongDongChanging(value);
					this.SendPropertyChanging();
					this._QLTuVungCongDong = value;
					this.SendPropertyChanged("QLTuVungCongDong");
					this.OnQLTuVungCongDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DuyetTu", DbType="Bit")]
		public System.Nullable<bool> DuyetTu
		{
			get
			{
				return this._DuyetTu;
			}
			set
			{
				if ((this._DuyetTu != value))
				{
					this.OnDuyetTuChanging(value);
					this.SendPropertyChanging();
					this._DuyetTu = value;
					this.SendPropertyChanged("DuyetTu");
					this.OnDuyetTuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XemTuVungSai", DbType="Bit")]
		public System.Nullable<bool> XemTuVungSai
		{
			get
			{
				return this._XemTuVungSai;
			}
			set
			{
				if ((this._XemTuVungSai != value))
				{
					this.OnXemTuVungSaiChanging(value);
					this.SendPropertyChanging();
					this._XemTuVungSai = value;
					this.SendPropertyChanged("XemTuVungSai");
					this.OnXemTuVungSaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QLThongTinWeb", DbType="Bit")]
		public System.Nullable<bool> QLThongTinWeb
		{
			get
			{
				return this._QLThongTinWeb;
			}
			set
			{
				if ((this._QLThongTinWeb != value))
				{
					this.OnQLThongTinWebChanging(value);
					this.SendPropertyChanging();
					this._QLThongTinWeb = value;
					this.SendPropertyChanged("QLThongTinWeb");
					this.OnQLThongTinWebChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QLDienDan", DbType="Bit")]
		public System.Nullable<bool> QLDienDan
		{
			get
			{
				return this._QLDienDan;
			}
			set
			{
				if ((this._QLDienDan != value))
				{
					this.OnQLDienDanChanging(value);
					this.SendPropertyChanging();
					this._QLDienDan = value;
					this.SendPropertyChanged("QLDienDan");
					this.OnQLDienDanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_Banbe", Storage="_Banbes", ThisKey="taikhoan", OtherKey="taikhoan")]
		public EntitySet<Banbe> Banbes
		{
			get
			{
				return this._Banbes;
			}
			set
			{
				this._Banbes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_Banbe1", Storage="_Banbes1", ThisKey="taikhoan", OtherKey="taikhoanban")]
		public EntitySet<Banbe> Banbes1
		{
			get
			{
				return this._Banbes1;
			}
			set
			{
				this._Banbes1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_TuVung", Storage="_TuVungs", ThisKey="taikhoan", OtherKey="taikhoan")]
		public EntitySet<TuVung> TuVungs
		{
			get
			{
				return this._TuVungs;
			}
			set
			{
				this._TuVungs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_CauHoi_DienDan", Storage="_CauHoi_DienDans", ThisKey="taikhoan", OtherKey="taikhoan")]
		public EntitySet<CauHoi_DienDan> CauHoi_DienDans
		{
			get
			{
				return this._CauHoi_DienDans;
			}
			set
			{
				this._CauHoi_DienDans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_Nhom_TuDien", Storage="_Nhom_TuDiens", ThisKey="taikhoan", OtherKey="taikhoan")]
		public EntitySet<Nhom_TuDien> Nhom_TuDiens
		{
			get
			{
				return this._Nhom_TuDiens;
			}
			set
			{
				this._Nhom_TuDiens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_TinNhan", Storage="_TinNhans", ThisKey="taikhoan", OtherKey="Nguoigoi")]
		public EntitySet<TinNhan> TinNhans
		{
			get
			{
				return this._TinNhans;
			}
			set
			{
				this._TinNhans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_TinNhan1", Storage="_TinNhans1", ThisKey="taikhoan", OtherKey="Nguoinhan")]
		public EntitySet<TinNhan> TinNhans1
		{
			get
			{
				return this._TinNhans1;
			}
			set
			{
				this._TinNhans1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_TraLoi_DienDan", Storage="_TraLoi_DienDans", ThisKey="taikhoan", OtherKey="taikhoan")]
		public EntitySet<TraLoi_DienDan> TraLoi_DienDans
		{
			get
			{
				return this._TraLoi_DienDans;
			}
			set
			{
				this._TraLoi_DienDans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_TuDien", Storage="_TuDiens", ThisKey="taikhoan", OtherKey="taikhoan")]
		public EntitySet<TuDien> TuDiens
		{
			get
			{
				return this._TuDiens;
			}
			set
			{
				this._TuDiens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Banbes(Banbe entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = this;
		}
		
		private void detach_Banbes(Banbe entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = null;
		}
		
		private void attach_Banbes1(Banbe entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung1 = this;
		}
		
		private void detach_Banbes1(Banbe entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung1 = null;
		}
		
		private void attach_TuVungs(TuVung entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = this;
		}
		
		private void detach_TuVungs(TuVung entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = null;
		}
		
		private void attach_CauHoi_DienDans(CauHoi_DienDan entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = this;
		}
		
		private void detach_CauHoi_DienDans(CauHoi_DienDan entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = null;
		}
		
		private void attach_Nhom_TuDiens(Nhom_TuDien entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = this;
		}
		
		private void detach_Nhom_TuDiens(Nhom_TuDien entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = null;
		}
		
		private void attach_TinNhans(TinNhan entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = this;
		}
		
		private void detach_TinNhans(TinNhan entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = null;
		}
		
		private void attach_TinNhans1(TinNhan entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung1 = this;
		}
		
		private void detach_TinNhans1(TinNhan entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung1 = null;
		}
		
		private void attach_TraLoi_DienDans(TraLoi_DienDan entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = this;
		}
		
		private void detach_TraLoi_DienDans(TraLoi_DienDan entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = null;
		}
		
		private void attach_TuDiens(TuDien entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = this;
		}
		
		private void detach_TuDiens(TuDien entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Nhom_TuDien")]
	public partial class Nhom_TuDien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _TuDienID;
		
		private string _taikhoan;
		
		private System.Nullable<bool> _Xem;
		
		private System.Nullable<bool> _Them;
		
		private System.Nullable<bool> _Xoa;
		
		private System.Nullable<bool> _Sua;
		
		private System.Nullable<bool> _dongy;
		
		private EntityRef<NguoiDung> _NguoiDung;
		
		private EntityRef<TuDien> _TuDien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTuDienIDChanging(System.Guid value);
    partial void OnTuDienIDChanged();
    partial void OntaikhoanChanging(string value);
    partial void OntaikhoanChanged();
    partial void OnXemChanging(System.Nullable<bool> value);
    partial void OnXemChanged();
    partial void OnThemChanging(System.Nullable<bool> value);
    partial void OnThemChanged();
    partial void OnXoaChanging(System.Nullable<bool> value);
    partial void OnXoaChanged();
    partial void OnSuaChanging(System.Nullable<bool> value);
    partial void OnSuaChanged();
    partial void OndongyChanging(System.Nullable<bool> value);
    partial void OndongyChanged();
    #endregion
		
		public Nhom_TuDien()
		{
			this._NguoiDung = default(EntityRef<NguoiDung>);
			this._TuDien = default(EntityRef<TuDien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuDienID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid TuDienID
		{
			get
			{
				return this._TuDienID;
			}
			set
			{
				if ((this._TuDienID != value))
				{
					if (this._TuDien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTuDienIDChanging(value);
					this.SendPropertyChanging();
					this._TuDienID = value;
					this.SendPropertyChanged("TuDienID");
					this.OnTuDienIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taikhoan", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string taikhoan
		{
			get
			{
				return this._taikhoan;
			}
			set
			{
				if ((this._taikhoan != value))
				{
					if (this._NguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OntaikhoanChanging(value);
					this.SendPropertyChanging();
					this._taikhoan = value;
					this.SendPropertyChanged("taikhoan");
					this.OntaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Xem", DbType="Bit")]
		public System.Nullable<bool> Xem
		{
			get
			{
				return this._Xem;
			}
			set
			{
				if ((this._Xem != value))
				{
					this.OnXemChanging(value);
					this.SendPropertyChanging();
					this._Xem = value;
					this.SendPropertyChanged("Xem");
					this.OnXemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Them", DbType="Bit")]
		public System.Nullable<bool> Them
		{
			get
			{
				return this._Them;
			}
			set
			{
				if ((this._Them != value))
				{
					this.OnThemChanging(value);
					this.SendPropertyChanging();
					this._Them = value;
					this.SendPropertyChanged("Them");
					this.OnThemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Xoa", DbType="Bit")]
		public System.Nullable<bool> Xoa
		{
			get
			{
				return this._Xoa;
			}
			set
			{
				if ((this._Xoa != value))
				{
					this.OnXoaChanging(value);
					this.SendPropertyChanging();
					this._Xoa = value;
					this.SendPropertyChanged("Xoa");
					this.OnXoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sua", DbType="Bit")]
		public System.Nullable<bool> Sua
		{
			get
			{
				return this._Sua;
			}
			set
			{
				if ((this._Sua != value))
				{
					this.OnSuaChanging(value);
					this.SendPropertyChanging();
					this._Sua = value;
					this.SendPropertyChanged("Sua");
					this.OnSuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dongy", DbType="Bit")]
		public System.Nullable<bool> dongy
		{
			get
			{
				return this._dongy;
			}
			set
			{
				if ((this._dongy != value))
				{
					this.OndongyChanging(value);
					this.SendPropertyChanging();
					this._dongy = value;
					this.SendPropertyChanged("dongy");
					this.OndongyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_Nhom_TuDien", Storage="_NguoiDung", ThisKey="taikhoan", OtherKey="taikhoan", IsForeignKey=true)]
		public NguoiDung NguoiDung
		{
			get
			{
				return this._NguoiDung.Entity;
			}
			set
			{
				NguoiDung previousValue = this._NguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._NguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiDung.Entity = null;
						previousValue.Nhom_TuDiens.Remove(this);
					}
					this._NguoiDung.Entity = value;
					if ((value != null))
					{
						value.Nhom_TuDiens.Add(this);
						this._taikhoan = value.taikhoan;
					}
					else
					{
						this._taikhoan = default(string);
					}
					this.SendPropertyChanged("NguoiDung");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TuDien_Nhom_TuDien", Storage="_TuDien", ThisKey="TuDienID", OtherKey="TudienID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public TuDien TuDien
		{
			get
			{
				return this._TuDien.Entity;
			}
			set
			{
				TuDien previousValue = this._TuDien.Entity;
				if (((previousValue != value) 
							|| (this._TuDien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TuDien.Entity = null;
						previousValue.Nhom_TuDiens.Remove(this);
					}
					this._TuDien.Entity = value;
					if ((value != null))
					{
						value.Nhom_TuDiens.Add(this);
						this._TuDienID = value.TudienID;
					}
					else
					{
						this._TuDienID = default(System.Guid);
					}
					this.SendPropertyChanged("TuDien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TinNhan")]
	public partial class TinNhan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _TinNhanID;
		
		private string _Nguoigoi;
		
		private string _Nguoinhan;
		
		private string _NoiDung;
		
		private System.Nullable<System.DateTime> _NgayGoi;
		
		private System.Nullable<bool> _XacNhan;
		
		private EntityRef<NguoiDung> _NguoiDung;
		
		private EntityRef<NguoiDung> _NguoiDung1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTinNhanIDChanging(System.Guid value);
    partial void OnTinNhanIDChanged();
    partial void OnNguoigoiChanging(string value);
    partial void OnNguoigoiChanged();
    partial void OnNguoinhanChanging(string value);
    partial void OnNguoinhanChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnNgayGoiChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayGoiChanged();
    partial void OnXacNhanChanging(System.Nullable<bool> value);
    partial void OnXacNhanChanged();
    #endregion
		
		public TinNhan()
		{
			this._NguoiDung = default(EntityRef<NguoiDung>);
			this._NguoiDung1 = default(EntityRef<NguoiDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinNhanID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid TinNhanID
		{
			get
			{
				return this._TinNhanID;
			}
			set
			{
				if ((this._TinNhanID != value))
				{
					this.OnTinNhanIDChanging(value);
					this.SendPropertyChanging();
					this._TinNhanID = value;
					this.SendPropertyChanged("TinNhanID");
					this.OnTinNhanIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nguoigoi", DbType="VarChar(30)")]
		public string Nguoigoi
		{
			get
			{
				return this._Nguoigoi;
			}
			set
			{
				if ((this._Nguoigoi != value))
				{
					if (this._NguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNguoigoiChanging(value);
					this.SendPropertyChanging();
					this._Nguoigoi = value;
					this.SendPropertyChanged("Nguoigoi");
					this.OnNguoigoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nguoinhan", DbType="VarChar(30)")]
		public string Nguoinhan
		{
			get
			{
				return this._Nguoinhan;
			}
			set
			{
				if ((this._Nguoinhan != value))
				{
					if (this._NguoiDung1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNguoinhanChanging(value);
					this.SendPropertyChanging();
					this._Nguoinhan = value;
					this.SendPropertyChanged("Nguoinhan");
					this.OnNguoinhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(4000)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayGoi", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NgayGoi
		{
			get
			{
				return this._NgayGoi;
			}
			set
			{
				if ((this._NgayGoi != value))
				{
					this.OnNgayGoiChanging(value);
					this.SendPropertyChanging();
					this._NgayGoi = value;
					this.SendPropertyChanged("NgayGoi");
					this.OnNgayGoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XacNhan", DbType="Bit")]
		public System.Nullable<bool> XacNhan
		{
			get
			{
				return this._XacNhan;
			}
			set
			{
				if ((this._XacNhan != value))
				{
					this.OnXacNhanChanging(value);
					this.SendPropertyChanging();
					this._XacNhan = value;
					this.SendPropertyChanged("XacNhan");
					this.OnXacNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_TinNhan", Storage="_NguoiDung", ThisKey="Nguoigoi", OtherKey="taikhoan", IsForeignKey=true)]
		public NguoiDung NguoiDung
		{
			get
			{
				return this._NguoiDung.Entity;
			}
			set
			{
				NguoiDung previousValue = this._NguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._NguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiDung.Entity = null;
						previousValue.TinNhans.Remove(this);
					}
					this._NguoiDung.Entity = value;
					if ((value != null))
					{
						value.TinNhans.Add(this);
						this._Nguoigoi = value.taikhoan;
					}
					else
					{
						this._Nguoigoi = default(string);
					}
					this.SendPropertyChanged("NguoiDung");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_TinNhan1", Storage="_NguoiDung1", ThisKey="Nguoinhan", OtherKey="taikhoan", IsForeignKey=true)]
		public NguoiDung NguoiDung1
		{
			get
			{
				return this._NguoiDung1.Entity;
			}
			set
			{
				NguoiDung previousValue = this._NguoiDung1.Entity;
				if (((previousValue != value) 
							|| (this._NguoiDung1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiDung1.Entity = null;
						previousValue.TinNhans1.Remove(this);
					}
					this._NguoiDung1.Entity = value;
					if ((value != null))
					{
						value.TinNhans1.Add(this);
						this._Nguoinhan = value.taikhoan;
					}
					else
					{
						this._Nguoinhan = default(string);
					}
					this.SendPropertyChanged("NguoiDung1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TraLoi_DienDan")]
	public partial class TraLoi_DienDan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _TraLoiID;
		
		private string _taikhoan;
		
		private System.Nullable<System.Guid> _CauHoiID;
		
		private string _Noidung;
		
		private System.Nullable<System.DateTime> _NgayGoi;
		
		private EntityRef<CauHoi_DienDan> _CauHoi_DienDan;
		
		private EntityRef<NguoiDung> _NguoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTraLoiIDChanging(System.Guid value);
    partial void OnTraLoiIDChanged();
    partial void OntaikhoanChanging(string value);
    partial void OntaikhoanChanged();
    partial void OnCauHoiIDChanging(System.Nullable<System.Guid> value);
    partial void OnCauHoiIDChanged();
    partial void OnNoidungChanging(string value);
    partial void OnNoidungChanged();
    partial void OnNgayGoiChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayGoiChanged();
    #endregion
		
		public TraLoi_DienDan()
		{
			this._CauHoi_DienDan = default(EntityRef<CauHoi_DienDan>);
			this._NguoiDung = default(EntityRef<NguoiDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TraLoiID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid TraLoiID
		{
			get
			{
				return this._TraLoiID;
			}
			set
			{
				if ((this._TraLoiID != value))
				{
					this.OnTraLoiIDChanging(value);
					this.SendPropertyChanging();
					this._TraLoiID = value;
					this.SendPropertyChanged("TraLoiID");
					this.OnTraLoiIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taikhoan", DbType="VarChar(30)")]
		public string taikhoan
		{
			get
			{
				return this._taikhoan;
			}
			set
			{
				if ((this._taikhoan != value))
				{
					if (this._NguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OntaikhoanChanging(value);
					this.SendPropertyChanging();
					this._taikhoan = value;
					this.SendPropertyChanged("taikhoan");
					this.OntaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CauHoiID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> CauHoiID
		{
			get
			{
				return this._CauHoiID;
			}
			set
			{
				if ((this._CauHoiID != value))
				{
					if (this._CauHoi_DienDan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCauHoiIDChanging(value);
					this.SendPropertyChanging();
					this._CauHoiID = value;
					this.SendPropertyChanged("CauHoiID");
					this.OnCauHoiIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Noidung", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Noidung
		{
			get
			{
				return this._Noidung;
			}
			set
			{
				if ((this._Noidung != value))
				{
					this.OnNoidungChanging(value);
					this.SendPropertyChanging();
					this._Noidung = value;
					this.SendPropertyChanged("Noidung");
					this.OnNoidungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayGoi", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NgayGoi
		{
			get
			{
				return this._NgayGoi;
			}
			set
			{
				if ((this._NgayGoi != value))
				{
					this.OnNgayGoiChanging(value);
					this.SendPropertyChanging();
					this._NgayGoi = value;
					this.SendPropertyChanged("NgayGoi");
					this.OnNgayGoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CauHoi_DienDan_TraLoi_DienDan", Storage="_CauHoi_DienDan", ThisKey="CauHoiID", OtherKey="CauHoiID", IsForeignKey=true)]
		public CauHoi_DienDan CauHoi_DienDan
		{
			get
			{
				return this._CauHoi_DienDan.Entity;
			}
			set
			{
				CauHoi_DienDan previousValue = this._CauHoi_DienDan.Entity;
				if (((previousValue != value) 
							|| (this._CauHoi_DienDan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CauHoi_DienDan.Entity = null;
						previousValue.TraLoi_DienDans.Remove(this);
					}
					this._CauHoi_DienDan.Entity = value;
					if ((value != null))
					{
						value.TraLoi_DienDans.Add(this);
						this._CauHoiID = value.CauHoiID;
					}
					else
					{
						this._CauHoiID = default(Nullable<System.Guid>);
					}
					this.SendPropertyChanged("CauHoi_DienDan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_TraLoi_DienDan", Storage="_NguoiDung", ThisKey="taikhoan", OtherKey="taikhoan", IsForeignKey=true, DeleteRule="CASCADE")]
		public NguoiDung NguoiDung
		{
			get
			{
				return this._NguoiDung.Entity;
			}
			set
			{
				NguoiDung previousValue = this._NguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._NguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiDung.Entity = null;
						previousValue.TraLoi_DienDans.Remove(this);
					}
					this._NguoiDung.Entity = value;
					if ((value != null))
					{
						value.TraLoi_DienDans.Add(this);
						this._taikhoan = value.taikhoan;
					}
					else
					{
						this._taikhoan = default(string);
					}
					this.SendPropertyChanged("NguoiDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TuDien")]
	public partial class TuDien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _TudienID;
		
		private string _TenTuDien;
		
		private System.Nullable<bool> _CongDong;
		
		private string _taikhoan;
		
		private EntitySet<TuVung> _TuVungs;
		
		private EntitySet<Nhom_TuDien> _Nhom_TuDiens;
		
		private EntityRef<NguoiDung> _NguoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTudienIDChanging(System.Guid value);
    partial void OnTudienIDChanged();
    partial void OnTenTuDienChanging(string value);
    partial void OnTenTuDienChanged();
    partial void OnCongDongChanging(System.Nullable<bool> value);
    partial void OnCongDongChanged();
    partial void OntaikhoanChanging(string value);
    partial void OntaikhoanChanged();
    #endregion
		
		public TuDien()
		{
			this._TuVungs = new EntitySet<TuVung>(new Action<TuVung>(this.attach_TuVungs), new Action<TuVung>(this.detach_TuVungs));
			this._Nhom_TuDiens = new EntitySet<Nhom_TuDien>(new Action<Nhom_TuDien>(this.attach_Nhom_TuDiens), new Action<Nhom_TuDien>(this.detach_Nhom_TuDiens));
			this._NguoiDung = default(EntityRef<NguoiDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TudienID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid TudienID
		{
			get
			{
				return this._TudienID;
			}
			set
			{
				if ((this._TudienID != value))
				{
					this.OnTudienIDChanging(value);
					this.SendPropertyChanging();
					this._TudienID = value;
					this.SendPropertyChanged("TudienID");
					this.OnTudienIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTuDien", DbType="NVarChar(40)")]
		public string TenTuDien
		{
			get
			{
				return this._TenTuDien;
			}
			set
			{
				if ((this._TenTuDien != value))
				{
					this.OnTenTuDienChanging(value);
					this.SendPropertyChanging();
					this._TenTuDien = value;
					this.SendPropertyChanged("TenTuDien");
					this.OnTenTuDienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CongDong", DbType="Bit")]
		public System.Nullable<bool> CongDong
		{
			get
			{
				return this._CongDong;
			}
			set
			{
				if ((this._CongDong != value))
				{
					this.OnCongDongChanging(value);
					this.SendPropertyChanging();
					this._CongDong = value;
					this.SendPropertyChanged("CongDong");
					this.OnCongDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taikhoan", DbType="VarChar(30)")]
		public string taikhoan
		{
			get
			{
				return this._taikhoan;
			}
			set
			{
				if ((this._taikhoan != value))
				{
					if (this._NguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OntaikhoanChanging(value);
					this.SendPropertyChanging();
					this._taikhoan = value;
					this.SendPropertyChanged("taikhoan");
					this.OntaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TuDien_TuVung", Storage="_TuVungs", ThisKey="TudienID", OtherKey="TuDienID")]
		public EntitySet<TuVung> TuVungs
		{
			get
			{
				return this._TuVungs;
			}
			set
			{
				this._TuVungs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TuDien_Nhom_TuDien", Storage="_Nhom_TuDiens", ThisKey="TudienID", OtherKey="TuDienID")]
		public EntitySet<Nhom_TuDien> Nhom_TuDiens
		{
			get
			{
				return this._Nhom_TuDiens;
			}
			set
			{
				this._Nhom_TuDiens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_TuDien", Storage="_NguoiDung", ThisKey="taikhoan", OtherKey="taikhoan", IsForeignKey=true, DeleteRule="CASCADE")]
		public NguoiDung NguoiDung
		{
			get
			{
				return this._NguoiDung.Entity;
			}
			set
			{
				NguoiDung previousValue = this._NguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._NguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiDung.Entity = null;
						previousValue.TuDiens.Remove(this);
					}
					this._NguoiDung.Entity = value;
					if ((value != null))
					{
						value.TuDiens.Add(this);
						this._taikhoan = value.taikhoan;
					}
					else
					{
						this._taikhoan = default(string);
					}
					this.SendPropertyChanged("NguoiDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TuVungs(TuVung entity)
		{
			this.SendPropertyChanging();
			entity.TuDien = this;
		}
		
		private void detach_TuVungs(TuVung entity)
		{
			this.SendPropertyChanging();
			entity.TuDien = null;
		}
		
		private void attach_Nhom_TuDiens(Nhom_TuDien entity)
		{
			this.SendPropertyChanging();
			entity.TuDien = this;
		}
		
		private void detach_Nhom_TuDiens(Nhom_TuDien entity)
		{
			this.SendPropertyChanging();
			entity.TuDien = null;
		}
	}
}
#pragma warning restore 1591
